language: java
install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "lores"

matrix:
  include:
    - jdk: openjdk8
      script: ./mvnw clean verify
      after_script:
        - bash ./notify_build.sh
    - jdk: openjdk11
      script: ./mvnw clean verify -Pjacoco && ./mvnw coveralls:report sonar:sonar 
      after_script:
        - bash ./notify_build.sh
    