language: java
install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

services:
  - xvfb
  - docker

addons:
  sonarcloud:
    organization: "lores"

matrix:
  include:
    - jdk: openjdk8
      script: ./mvnw clean verify
      after_script: bash ./notify_build.sh
    - jdk: openjdk11
      script: ./mvnw clean verify -Pjacoco && ./mvnw coveralls:report sonar:sonar 
      after_script: bash ./notify_build.sh
    - jdk: openjdk8
      if: type IN (pull_request)
      script: ./mvnw clean verify -Pmutation-tests
      after_script: bash ./notify_build.sh
    - jdk: openjdk8
      if: type IN (pull_request) OR branch IN (master)
      script: ./mvnw clean verify -Pe2e-tests
      after_script: bash ./notify_build.sh
    