language: java
install: true

jdk: openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "lores"
    
script:
  - ./mvnw clean verify -Pjacoco
  - ./mvnw coveralls:report sonar:sonar