language: java
install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "lores"

matrix:
  include:
    - jdk: openjdk8
      script: ./mvnw coveralls:report
    - jdk: openjdk11
      script: ./mvnw coveralls:report
    - jdk: openjdk11
      script: ./mvnw sonar:sonar 
    - jdk: openjdk11
      script: ./mvnw coveralls:report sonar:sonar 
    